### ISSUE TITLE
User/pass won't work

### ISSUE THREAD

**Issue by adizag** [linuxserver/docker-cloud9#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Installed trough docker compose.
when removing the user/pass env parameters I can get into the GUI, but when defining the user/pass I get the login popup which will never get me through although I entered the right user/pass

## Current Behavior
Can't login

## Steps to Reproduce
https://youtu.be/RCEc03nsjNQ

## Environment
**OS:** Ubuntu 18.04
**CPU architecture:** x86_64
**How docker service was installed:**
from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
```
    cloud9:
        image: ghcr.io/linuxserver/cloud9
        container_name: cloud9
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - GITURL=https://github.com/linuxserver/docker-cloud9.git #optional
            - USERNAME= user  #for example
            - PASSWORD= pass1234    #for example
        volumes:
            - ${USERDIR}/docker:/code #optional
            - /var/run/docker.sock:/var/run/docker.sock #optional
        ports:
            - 8800:8000
        restart: unless-stopped
```

## Docker logs
```
[s6-init] ensuring user provided files have correct perms...exited 0.


[fix-attrs.d] applying ownership & permissions fixes...


[fix-attrs.d] done.


[cont-init.d] executing container initialization scripts...


[cont-init.d] 01-envfile: executing... 


[cont-init.d] 01-envfile: exited 0.


[cont-init.d] 10-adduser: executing... 




-------------------------------------


          _         ()


         | |  ___   _    __


         | | / __| | |  /  \ 


         | | \__ \ | | | () |


         |_| |___/ |_|  \__/






Brought to you by linuxserver.io


-------------------------------------




To support LSIO projects visit:


https://www.linuxserver.io/donate/


-------------------------------------


GID/UID


-------------------------------------




User uid:    1000


User gid:    999


-------------------------------------




[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 30-config: executing... 


[cont-init.d] Setting permissions this may take some time


[cont-init.d] 30-config: exited 0.


[cont-init.d] 99-custom-scripts: executing... 


[custom-init] no custom files found exiting...


[cont-init.d] 99-custom-scripts: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.


Starting standalone


Connect server listening at http://172.18.0.17:8000


Using basic authentication


unable to patch engine.io


CDN: version standalone initialized /c9sdk/build


Started '/c9sdk/configs/standalone' with config 'standalone'!


Cloud9 is up and running


[cont-finish.d] executing container finish scripts...


[cont-finish.d] done.


[s6-finish] waiting for services.


[s6-finish] sending all processes the TERM signal.


[s6-finish] sending all processes the KILL signal and exiting.


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.


[s6-init] ensuring user provided files have correct perms...exited 0.


[fix-attrs.d] applying ownership & permissions fixes...


[fix-attrs.d] done.


[cont-init.d] executing container initialization scripts...


[cont-init.d] 01-envfile: executing... 


[cont-init.d] 01-envfile: exited 0.


[cont-init.d] 10-adduser: executing... 


usermod: no changes




-------------------------------------


          _         ()


         | |  ___   _    __


         | | / __| | |  /  \ 


         | | \__ \ | | | () |


         |_| |___/ |_|  \__/






Brought to you by linuxserver.io


-------------------------------------




To support LSIO projects visit:


https://www.linuxserver.io/donate/


-------------------------------------


GID/UID


-------------------------------------




User uid:    1000


User gid:    999


-------------------------------------




[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 30-config: executing... 


Lock exists just starting cloud9


[cont-init.d] Setting permissions this may take some time


[cont-init.d] 30-config: exited 0.


[cont-init.d] 99-custom-scripts: executing... 


[custom-init] no custom files found exiting...


[cont-init.d] 99-custom-scripts: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.


Starting standalone


Connect server listening at http://172.18.0.17:8000


Using basic authentication


unable to patch engine.io


CDN: version standalone initialized /c9sdk/build


Started '/c9sdk/configs/standalone' with config 'standalone'!


Cloud9 is up and running

```
