### ISSUE TITLE
Preference is lost to stop and start Container

### ISSUE THREAD

**Issue by dexter74** [linuxserver/docker-cloud9#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior:
When restarting the container, the preferences are save and load on startup.

## Current Behavior
During a clean stop of the container, restart of the machine and restart of the container the preferences are reset to zero. What is abnormal

## Steps to Reproduce
1. Install Portainer 2.0.1 
2. Create Stack with code in topic
3. Edit preference
4. Stop container with a panel portainer
5. Reboot VM
6. Start Container
7. Check Preference.

File: ~/.c9/user.settings

## Environment
**OS:** Debian 10
**CPU:** KVM (Virtual Machine)
**How docker service was installed:**
Docker repo. (Docker : 20.10.2 (Build: 2291f61 | Docker-compose: 1.27.4 (Build:  40524192)

## Command used to create docker container (run/create/compose/screenshot)
````yaml
version: 2.4
services:
  Cloud9:
    container_name: 'CN_Cloud9'
    image: 'linuxserver/cloud9'
    network_mode: 'bridge'
    restart: 'no'
    environment:
      PUID: '1001'
      PGID: '74240'
      TZ: 'Europe/Paris'
      USERNAME: 'admin'
      PASSWORD: 'admin'
    ports:
      - '1003:8000'
    volumes:
      - 'Cloud9:/code'
      - '/var/run/docker.sock:/var/run/docker.sock'
````

## Docker logs
````console
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    74240,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] Setting permissions this may take some time,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Starting standalone,
Connect server listening at http://172.17.0.5:8000,
Using basic authentication,

unable to patch engine.io,
CDN: version standalone initialized /c9sdk/build,
Started '/c9sdk/configs/standalone' with config 'standalone'!,

Cloud9 is up and running,
````

### **Screen 1:*** Edit Preference
![image](https://user-images.githubusercontent.com/35907/107000374-11655980-6788-11eb-83af-075384ef25c1.png)

### Screen 2: Stop Container
![image](https://user-images.githubusercontent.com/35907/107000845-dadc0e80-6788-11eb-8fc8-e6304e4a6c1f.png)

### **Screen 3:** Start Container
![image](https://user-images.githubusercontent.com/35907/107000863-e4fe0d00-6788-11eb-9e91-2a4e8cd10b6d.png)

### **Screen 4:** Check Preference
![image](https://user-images.githubusercontent.com/35907/107001134-69e92680-6789-11eb-8d07-9fc544566489.png)
